apiVersion: apps/v1
kind: Deployment
metadata:
    name: node-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: node-app
    template:
        metadata:
            labels:
                app: node-app
        spec:
            containers:
                - name: node-app
                  image: xgiovanni/node-app-devops:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000
            restartPolicy: Always
