on: push
name: Create and Publish image
jobs:
    build:
        name: Build and Publish Docker image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@main
            - name: Login to Docker hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ../Dockerfile
                  push: true
                  tags: xgiovanni/node-app-devops:latest, xgiovanni/node-app-devops:${{ github.sha }}
            - name: get nodes
              uses: steebchen/kubectl@v2.0.0
              with:
                  config: ${{ secrets.KUBE_CONFIG_DATA }}
                  command: get nodes
            - name: deploy to cluster
              uses: steebchen/kubectl@v2.0.0
              with:
                  config: ${{ secrets.KUBE_CONFIG_DATA }}
                  command: set image deployment/example-aks1 container=xgiovanni/node-app-devops:latest
