on: push
name: publish image
jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xgiovanni/node-app-devops
          tag_with_ref: true
          tag_with_sha: true
      - name: get nodes
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: get nodes
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image deployment/example-aks1 container=xgiovanni/node-app-devops:${{ github.sha }}
